### ISSUE TITLE
As a user, I need a dashboard for piloting the drone

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/drone#1]
## Overview
Let's create a simple dashboard that shows which signals are being sent to the server.

## Tasks
- [ ] Reuse theme from our [Rest2D2 project](https://rest2d2-ff500.firebaseapp.com/)
- [ ] Load handsfree.js
- [ ] Move forward/backward by leaning in/away
- [ ] Move up/down by lowering/raising head/body
- [ ] Turn by turning head
- [ ] Show logs
