### ISSUE TITLE
As a user, I need a webserver that accepts inputs from a client

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/drone#1]
## Overview
Using the existing server, let's build an API to receive inputs from the client.

## Tasks
- [ ] Create an express server
- [ ] Create a simple UI for manually sending inputs
- [ ] Send inputs via handsfreejs
